<h1>Instellingen inschrijfformulier</h1>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('settings/enrolment'));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php
    $element = $form->get('require_iban');
    ?>
    <label>
        <?= $this->formCheckbox($element) ?>
        <?= $element->getLabel() ?>
    </label>
    <?= $this->formElementErrors($element) ?>
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel('Opslaan');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
