version: '3.5'

services:
    nginx:
        image: abc-db.docker-registry.gewis.nl/gewisdb_nginx:latest
        env_file:
            - .env
        #        environment:
        #            - NGINX_REQUIRE_AUTH=
        depends_on:
            - web
        volumes:
            - gewisdb_public:/code/public:ro
            - gewisdb_logs:/etc/nginx/logs:rw
        networks:
            - gewisdb_network
        ports:
            - "9725:9725"
        restart: unless-stopped
    web:
        image: abc-db.docker-registry.gewis.nl/gewisdb_web:production
        env_file:
            - .env
#        environment:
#            - APP_ENV=
#            - COOKIE_DOMAIN=
#            - CHECKER_REPORT_MAIL=
#            - CHECKER_MEMBERSHIP_API_ENDPOINT=
#            - CHECKER_MEMBERSHIP_API_KEY=
#            - CHECKER_MEMBERSHIP_API_MAX_TOTAL_REQUESTS=
#            - CHECKER_MEMBERSHIP_API_MAX_MANUAL_REQUESTS=
#            - DOCTRINE_DEFAULT_HOST=
#            - DOCTRINE_DEFAULT_PORT=
#            - DOCTRINE_DEFAULT_USER=
#            - DOCTRINE_DEFAULT_PASSWORD=
#            - DOCTRINE_DEFAULT_DATABASE=
#            - DOCTRINE_REPORT_HOST=
#            - DOCTRINE_REPORT_PORT=
#            - DOCTRINE_REPORT_USER=
#            - DOCTRINE_REPORT_PASSWORD=
#            - DOCTRINE_REPORT_DATABASE=
        depends_on:
            - memcached
            - postfix
        volumes:
            - gewisdb_data:/code/data:rw
            - gewisdb_public:/code/public:rw
        networks:
            - gewisdb_network
        restart: unless-stopped
    memcached:
        image: memcached:1.6-alpine
        entrypoint:
            - memcached
            - -m 64
    postfix:
        image: juanluisbaptiste/postfix
        env_file:
            - .env
#        environment:
#            - SMTP_SERVER=
#            - SMTP_PORT=
#            - SMTP_USERNAME=
#            - SMTP_PASSWORD=
#            - SERVER_HOSTNAME=
        networks:
            - gewisdb_network
        restart: unless-stopped
        stop_grace_period: 60s

volumes:
    gewisdb_data:
    gewisdb_public:
    gewisdb_logs:

networks:
    gewisdb_network:
