<script>
    var urlTemplate = '<?= $this->url('donor/show', array('id' => '__ID__')) ?>';
    $(document).ready(function () {
        var maxResults = 32;
        var footer = $("#donors-result tfoot");
        var searchDonor = function (term) {
            // When no term is set, all the donor should be shown
            if (term.length >= 0) {
                $.ajax({
                    dataType: 'json',
                    url: '<?= $this->url('donor/search') ?>?q=' + term,
                    context: document.body
                }).done(function (data) {
                    var table = '';
                    $.each(data.json, function (idx, donor) {
                        var link = '';
                        link += '<a style="display: block; width: 100%; height: 100%;" href="' + urlTemplate.replace('__ID__', donor.id) + '">'
                        table += '<tr>';
                        table += '<td>' + link + donor.id + '</a></td>';
                        table += '<td>' + link + donor.fullName + '</a></td>';
                        table += '<td>' + link + donor.start + '</a></td>';
                        table += '<td>' + link + donor.amount + '</a></td>';
                        table += '</tr>';
                    });
                    $('#donors-result tbody').html(table);

                    if (data.json.length >= maxResults) {
                        footer.show();
                    } else {
                        footer.hide();
                    }
                });
            } else {
                $('#donors-result tbody').html('');
            }
        };

        $('#donor-search').keyup(function (e) {
            term = $(e.target).val();
            searchDonor(term)
        });
        searchDonor('');
        footer.hide();
    });
</script>
<form role="form">
    <div class="form-group">
        <label for="">Zoeken op donateur</label>
        <input type="text" class="form-control" placeholder="Zoek" id="donor-search" autofocus>
    </div>
</form>

<table class="table table-hover" id="donors-result">
    <thead>
        <tr>
            <th>#</th>
            <th>Naam</th>
            <th>Vanaf</th>
            <th>Donatie</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4"> Er zijn teveel resultaten om weer te geven. Probeer te filteren om andere resultaten te zien.</td>
        </tr>
    </tfoot>
</table>

<a href="<?= $this->url('donor/register') ?>" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Registreer donateur</a>
